### ISSUE TITLE
Reset to the default PS theme

### ISSUE THREAD

**Issue by mayureshs** [dracula/powershell#16]
How do you uninstall this theme and reset to the default powershell theme ?

**Comment by machine1104** [comment]
i have the same problem

**Comment by mayureshs** [comment]
Any update on this issue ?

**Comment by waf** [comment]
@mayureshs and @machine1104 I've just opened PR #17 that adds some basic support for this. It's pretty tricky and generally tools like ColorTool and Concfg don't support this because of that trickiness. However, I think this PR will help you uninstall it.

Could you please [download the zip file in that PR](https://github.com/dracula/powershell/raw/3d84a753670ee3c993a20036eec222e397094c8c/dist/ColorTool.zip) and run the `uninstall.cmd` inside it? Then, running powershell from the start menu or from Window's "Run" dialog should be back to the familiar blue and white. Please let me know how it goes.

**Comment by mayureshs** [comment]
Below is the snapshot of running the uninstall file. However reopening PS still has the same theme. Does not look like the uninstall worked.

![image](https://user-images.githubusercontent.com/1014702/60124407-2cb85800-974f-11e9-960b-45e2f9d07e21.png)

![image](https://user-images.githubusercontent.com/1014702/60124512-61c4aa80-974f-11e9-8706-4894e061a368.png)

**Comment by waf** [comment]
Thanks for reporting back @mayureshs. How are you opening powershell? Through the start menu or some other way?

- If through some other shortcut, please try using the start menu, and if that works, recreate your shortcut.
- If through the start menu, could you please send me the shortcut file (the `.lnk` file) so I can compare it to my machine?
- If through the windows "Run" dialog, could you please send me the export of the registry key `HKEY_CURRENT_USER\Console`?

**Comment by mayureshs** [comment]
Thanks for responding @waf.
When I search for powershell , I get two options "Windows PowerShell" and powershell.exe. Selecting Windows PowerShell does not seem to have restored the original theme, but selecting powershell.exe is showing the original PS theme (see screenshot). I am not able to attach an .lnk file to this thread.
Windows PowerShell shortcut is from \Users\AppData\Roaming ... folder while powershell.exe is from Windows\System32 folder

![image](https://user-images.githubusercontent.com/1014702/60182676-5d010480-97ea-11e9-9a0e-a2758b95f3f0.png)

**Comment by waf** [comment]
Thanks. That filesize doesn't look right in the top window in your screenshot. Is this the full path?

```
\Users\<user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Windows PowerShell\Windows PowerShell.lnk
```

I'm expecting it to be 2,494 bytes instead of the 1,756 bytes shown. It should be the same as the downloaded one in ColorTool.zip's `uninstall` folder (the uninstall command simply copies `\uninstall\Windows PowerShell.lnk` to your start menu). 

Can you please try running the shortcut from inside ColorTool.zip's uninstall directory? If that works, and your start menu is still not working, then something's wrong with the uninstall command. If it doesn't work, then I'd appreciate it if you could export the registry key `HKEY_CURRENT_USER\Console` and either paste or upload it here so I can understand the differences.

**Comment by mayureshs** [comment]
Running the uninstall command worked and i did verify the file size now increased to 2.47 KB. Thanks for your assistance @waf

**Comment by waf** [comment]
Great, glad to hear it worked. Thanks for raising this.

@machine1104 I think this should work for you now, please try it out. I'll close this issue now, but feel free to reopen or add a new issue.
