### ISSUE TITLE
Colours not working

### ISSUE THREAD

**Issue by JRCrawford** [dracula/powershell#22]
I've tried to get the colours working but all I get is this: 
![image](https://user-images.githubusercontent.com/16747994/64804971-e45b4a00-d587-11e9-827c-31de4fb23965.png)

Is there some settings I'm missing?

**Comment by waf** [comment]
@JRCrawford thanks for reporting. I solved a similar problem some time ago, but looks like it's not fully solved across all systems.

An immediate fix for you is to go into the [console properties](https://www.makeuseof.com/tag/change-colors-command-prompt/) and set the foreground and background colors. The color palette is already correct, but you need to point the foreground/background options to the correct existing color. The foreground should be the whiteish color (8th from the left) and the background should be the dark color (first from the left).

 The root of the issue is that Windows shortcut files (.lnk) can cache arbitrary color properties, making it difficult to create a consistent view, depending on how you open powershell.

If you have time, I'd appreciate it if you told me how you're opening powershell, and if you open it from the "windows run dialog" do you see different behavior? Thanks!

**Comment by JRCrawford** [comment]
@waf I'd love to help. I'm actually more of a Linux guy having used zsh (with oh-my-zsh) a lot, but our company has decieded to move over to O365 and use Windows instead. PS has however come a long way and I love what you've done with the styles.

To provide the steps I did the following:

- I first ran (in administrator mode) PS.
- I then installed chocolatey `Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`
- I then installed posh-git `choco install poshgit`
- I then did all steps (1,2,3) of your "Colors Installation" guide
- When I booted up PS I noticed that I had not enabled "unknown scripts to be executed" (or something like that)
- I then ran the command `Set-ExecutionPolicy RemoteSigned` to allow scripts to be executed

But even after restarting PS several times I still got the unusual colour.

**Comment by JRCrawford** [comment]
*update* So I've noticed that I did some steps for the CMD instead of PS. I have now done the following:

- Opened PS in admin mode
- ran `Install-Module -Name PowerShellGet -Force`
- ran `Install-Module -Name posh-git -AllowPrerelease -Force`
- Checked my version (it was indeed v2 so no issues)
- Added the extra code to my $profile file so it [looks like this](https://gist.github.com/JRCrawford/4bbd03ba3fa023ed2561d63c33498c80) 

However it now looks like this.  I think I made it a bit worse. 
![image](https://user-images.githubusercontent.com/16747994/64855080-02bc5680-d617-11e9-843c-1b42c3e66758.png)

**Comment by waf** [comment]
@JRCrawford thanks! Would you be able to export the following registery key and share it with me?

HKEY_CURRENT_USER\Console

This will list your current console configurations to a plain-text file, so I can see which configuration has the issue. Thanks!

**Comment by JRCrawford** [comment]
@waf sorry for the delay, I was out this weekend.  Anyway I was able to get this working after tweaking with some of the `$profile` settings and as such it looks great now as seen below.
![image](https://user-images.githubusercontent.com/16747994/64943521-d9443a80-d863-11e9-8bcf-88a849f3b133.png) (so I think we can close this issue).

I've attached my reg key just in case you wanted to look at it. You can see that [over here](https://gist.github.com/JRCrawford/b605a3788e0b96e4c7af9f485ba3398b)

**Comment by waf** [comment]
Thanks @JRCrawford. The only odd thing I see in the registry file is the `"ScreenColors"=dword:00000077` line. This means that your foreground color index (7) is the same as your background color index (7), which would make the terminal unusable. It should be `"ScreenColors"=dword:00000070`.

If you start powershell from the Windows Run Dialog (Win+R) is it working correctly? If so, great, I'll keep this issue closed. If not, rerunning the `install.cmd` should fix the problem.
