### ISSUE TITLE
When running a command in the powershell console, the window will shaking (refresh?)

### ISSUE THREAD

**Issue by LittleNewton** [dracula/powershell#26]
> If you're reporting an UI issue, make sure you take a screenshot that shows the actual bug.
I want to show you a small video about this. 

[Youtube Bug Video](https://www.youtube.com/watch?v=onxscM6f3HA)

Thank you.

**Comment by waf** [comment]
Thanks @LittleNewton. This seems similar to bug https://github.com/PowerShell/PowerShell/issues/7863 reported in PSReadLine (which this Dracula project uses). The video attached to that bug report is very similar.

That bug should have been fixed in recent versions of PSReadLine. Which version do you have? You can get the PSReadLine version using:

```powershell
$v = (Get-Module PSReadline).Version
$m = Get-Content "$(Split-Path -Parent (Get-Module PSReadLine).Path)\PSReadLine.psd1" | Select-String "Prerelease = '(.*)'"
if ($m) {
    $v = "$v-" + $m.Matches[0].Groups[1].Value
}
"PSReadline version: $v"
```

**Comment by angryyogurt** [comment]
I got very similar problem with dracula theme and consolas font. My PowerShell window shakes when I press `TAB` to auto complete command.

PowerShell 6.2.3
PSReadline version: 2.0.0-beta3
@waf

**Comment by waf** [comment]
Sorry for the slow response on this. I'm pretty sure it's an issue with the upstream PSReadline repository, but I've been unable to confirm that.

PSReadline is now out of beta. If you upgrade the module with `Update-Module PSReadline -Force`, then restart the terminal, is the issue fixed?

If not, I'll need to find a way to install that doesn't require PSReadline, potentially using concfg or some other tool.

**Comment by angryyogurt** [comment]
@waf no, it still has problem. Everytime I press `TAB`, powershell's content shakes once (seems like font changes quickly), and the PS window momently grows wider (not every time, maybe 3 of 10).

**Comment by waf** [comment]
@AngryYogurt thanks. If you disable PSReadline (`remove-module psreadline` will disable it for the current window) do you still get the shaking?

**Comment by angryyogurt** [comment]
@waf disable PSReadline also changes font, everything is ok now.

**Comment by waf** [comment]
@AngryYogurt I think this issue is tracking the bug in the PSReadLine repository: https://github.com/PowerShell/PSReadLine/issues/964

It says "I investigated the font flickering issue on CJK locale machines" which sounds like exactly what you're seeing.

There is a possible workaround here: https://github.com/PowerShell/PSReadLine/issues/964#issuecomment-601758285

**Comment by waf** [comment]
I'm going to close this issue, as it's being tracked by the above PSReadLine issue.

It's unfortunate that PSReadline has a problem with CJK characters. There is the workaround I linked to in my previous comment, additionally disabling PSReadline would work too.
