### ISSUE TITLE
The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set. At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:16 char:1

### ISSUE THREAD

**Issue by gawronix** [dracula/powershell#32]
Help me fix this...
The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:14 char:50
+ $GitPromptSettings.DefaultPromptPrefix.Text = "$([char]0x2192) " # ar ...
+                                                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:15 char:1
+ $GitPromptSettings.DefaultPromptPrefix.ForegroundColor = [ConsoleColo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:16 char:1
+ $GitPromptSettings.DefaultPromptPath.ForegroundColor =[ConsoleColor]: ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'Text' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:17 char:50
+ $GitPromptSettings.DefaultPromptSuffix.Text = "$([char]0x203A) " # ch ...
+                                                  ~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:18 char:1
+ $GitPromptSettings.DefaultPromptSuffix.ForegroundColor = [ConsoleColo ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:20 char:1
+ $GitPromptSettings.BeforeStatus.ForegroundColor = [ConsoleColor]::Blu ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:21 char:1
+ $GitPromptSettings.BranchColor.ForegroundColor = [ConsoleColor]::Blue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

The property 'ForegroundColor' cannot be found on this object. Verify that the property exists and can be set.
At C:\Users\grzeg\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1:22 char:1
+ $GitPromptSettings.AfterStatus.ForegroundColor = [ConsoleColor]::Blue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

![error](https://user-images.githubusercontent.com/30899138/83401018-3f79e900-a404-11ea-937d-b9e2854366e0.png)

**Comment by kevin-tong-msft** [comment]
I have the same issue.

**Comment by kevin-tong-msft** [comment]
According to https://github.com/dahlbyk/posh-git/issues/588, `DefaultPromptPath.ForegroundColor` only works on posh-git v1.0.0-beta2.
Running `Update-Module posh-git -RequiredVersion 1.0.0-beta2 -AllowPrerelease` works for me.

**Comment by leo-jansen** [comment]
eu estava com o mesmo problema, aconteceu pq não estava com posh-git, consegui instalar o posh-git seguindo a documentação no site do git, é só seguir o passo-passo.
https://git-scm.com/book/en/v2/Appendix-A:-Git-in-Other-Environments-Git-in-PowerShell

**Comment by gawronix** [comment]
Now i get smth like this.... before you say, i get the same result in normal powershell window...
![image](https://user-images.githubusercontent.com/30899138/84760711-b1d3f700-afc8-11ea-95cc-baaf3b6cb5ff.png)

**Comment by waf** [comment]
Hi @gawronix, can you please paste the output of the following two commands?

- `(get-module posh-git).Version`
- `(get-module psreadline).Version`

Thanks!

**Comment by kaellego** [comment]
> According to [dahlbyk/posh-git#588](https://github.com/dahlbyk/posh-git/issues/588), `DefaultPromptPath.ForegroundColor` only works on posh-git v1.0.0-beta2.
> Running `Update-Module posh-git -RequiredVersion 1.0.0-beta2 -AllowPrerelease` works for me.

An update for those experiencing problems
`Update-Module posh-git -RequiredVersion 1.0.0-beta4 -AllowPrerelease -Force`

**Comment by LukeSavefrogs** [comment]
### Problem
I encountered the same problem as well as an error saying i **didn't have** `-AllowPrerelease`. I tried to update both `PSReadLine` and `PowerShellGet` as said in the guide but that didn't work...

### Solution 
Turns out i had **different versions** running of both, so the PowerShell didn't know which to pick and insisted on using the 1.0 version.

In order to fix that i had to **remove the old versions** as said in [**this guide**](https://www.locktar.nl/programming/powershell/upgrading-powershellget-to-the-latest-version/). After that and restarting all is working.

---

### Edit
After running the operations described in the guide i linked before i was in a situation where typing `Get-Module PowerShellGet` would return nothing (so i couldn't check the version) but using `Get-Module powershellget -ListAvailable` i would find the correct module.

![The error](https://user-images.githubusercontent.com/33452387/90991064-8eb85b80-e5a6-11ea-8a68-f1beff1ea344.png)

#### Solution
To **fix** that i had to run `Update-Module -Name PowerShellGet` so that the version would stay unchanged since it was already updated but the module would be returned  from the `Get-Module` call. You can see by yourself in the next screenshot the situation _before_ the fix (red border) and the situation _after_ the fix (green border)

![After fixing](https://user-images.githubusercontent.com/33452387/90991151-55342000-e5a7-11ea-99de-05bde2fc122f.png)

If the `Update-Module` call fails, you have to loosen the Execution Policies by sending `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`. Now it should work fine. If you do so **MAKE SURE TO REVERT TO HOW IT WAS BEFORE** by sending `Set-ExecutionPolicy -ExecutionPolicy Default` after the `Update-Module` command has completed successfully!!

### Final result
Now it **works everything** and when i start the Powershell i **don't see** `The property 'xxxxx' cannot be found on this object. Verify that the property exists and can be set` **errors** :)  

![image](https://user-images.githubusercontent.com/33452387/90991204-b0fea900-e5a7-11ea-8b2a-86fc17641a34.png)


Hope i can be helpful to someone ^^

**Comment by waf** [comment]
I've reworked the install instructions, and added a link to @LukeSavefrogs's troubleshooting steps and information. Thanks for putting it together!

**Comment by astroahad** [comment]
Thank you!
