### ISSUE TITLE
[Question] Home dir ~ symbol on cmd theme

### ISSUE THREAD

**Issue by jakiisheep** [dracula/powershell#45]
So this is kind of a question rather than an issue but, is it possible to have the ~ (Tilda, home symbol) (like on Linux) instead of C:\Users\username on the cmd theme?

**Comment by waf** [comment]
Unfortunately, I don't think so (I've done some searching and did not find a way). PowerShell can do it because it allows custom prompt functions, but I think cmd.exe only supports a limited set of variables, none of which do what we want.

The cheap answer is that from cmd.exe, run powershell.exe, but that's cheating 😃

**Comment by jakiisheep** [comment]
Nevermind then, I would use PowerShell more than cmd but because cmd loads faster and I can quickly type in a command I need so I use it more. I have a lot of commands in my PowerShell profile so that's slowing it down but it looks amazing with all commands in the profile :) 

Anyways, thank you for at least searching for a solution.
