### ISSUE TITLE
Wrong colors 

### ISSUE THREAD

**Issue by s-kzmchv** [dracula/powershell#48]
Hello, after installation I get the wrong colors. Could you help me, please? 
![image](https://user-images.githubusercontent.com/30108960/109613632-7b341180-7b42-11eb-9255-eb5fd2b461d2.png)
The command line works fine, but not powershell.
![image](https://user-images.githubusercontent.com/30108960/109613733-a1f24800-7b42-11eb-84ec-76221b4cbfd0.png)

**Comment by waf** [comment]
Hi @s-kzmchv. If you right-click on the titlebar of PowerShell and go to Properties -> Colors, can you check which color the "Screen Text" is? My guess is that it's pointing to index 6, rather than index 7. Maybe some earlier theme changed the index.

![image](https://user-images.githubusercontent.com/97195/109629210-30cc8800-7b76-11eb-9f61-7e0ec0c141c0.png)

You might also have to make the same change to the "Default" menu item above the "Properties" menu item.

**Comment by s-kzmchv** [comment]
Yes! Thank you!
